pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/alovba1/gitdevops.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                bat './gradlew build'
            }
        }
     
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    bat './gradlew sonarqube'
                }
            }
        }
    }
}
